/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package model;

import javax.swing.JLabel;

/**
 *
 * @author lieutuanvu
 */
public class oSo extends javax.swing.JPanel {

    /**
     * Creates new form oSoJPanel
     */
    public oSo() {
        initComponents();
    }

    public oSo(String numberDisplay) {
        initComponents();
        oSoJLabelNumber.setText(numberDisplay);
        oSoJLabelNumber.setVisible(true);
        oSoRootJPanel.validate();
        oSoRootJPanel.repaint();

    }
    public void highlight(){
        this.oSoRootJPanel.setBackground(new java.awt.Color(234, 77, 122));
    }
    public void unHighlight(){
        this.oSoRootJPanel.setBackground(new java.awt.Color(255, 204, 153));
    }
    public void setOSO(String numberDisplay){
        oSoJLabelNumber.setText(numberDisplay);
        oSoJLabelNumber.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oSoRootJPanel = new javax.swing.JPanel();
        oSoJLabelNumber = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(45, 45));
        setSize(new java.awt.Dimension(45, 45));

        oSoRootJPanel.setBackground(new java.awt.Color(255, 204, 153));
        oSoRootJPanel.setPreferredSize(new java.awt.Dimension(45, 45));
        oSoRootJPanel.setSize(new java.awt.Dimension(45, 45));

        oSoJLabelNumber.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        oSoJLabelNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout oSoRootJPanelLayout = new javax.swing.GroupLayout(oSoRootJPanel);
        oSoRootJPanel.setLayout(oSoRootJPanelLayout);
        oSoRootJPanelLayout.setHorizontalGroup(
            oSoRootJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oSoJLabelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );
        oSoRootJPanelLayout.setVerticalGroup(
            oSoRootJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oSoJLabelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oSoRootJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oSoRootJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel oSoJLabelNumber;
    private javax.swing.JPanel oSoRootJPanel;
    // End of variables declaration//GEN-END:variables
}
