/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nienluancoso;

import java.util.LinkedList;
import javax.swing.JPanel;
import javax.swing.border.TitledBorder;
import model.listSort;
import model.oSo;

/**
 *
 * @author lieutuanvu
 */
public class viewWithoutCompareJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewWithoutCompareJPanel
     */
    public viewWithoutCompareJPanel(LinkedList<oSo> arrayListOSo, JPanel viewRootJPanel, int firstAlgorithmSelected) {
        for (int i = 0; i < arrayListOSo.size(); i++) {
            arrayListOSo.get(i).setLocation(viewRootJPanel.getSize().width / 2 + (i - arrayListOSo.size() / 2) * 90, viewRootJPanel.getSize().height / 2);
            arrayListOSo.get(i).setVisible(true);
            this.add(arrayListOSo.get(i));
        }
        if (firstAlgorithmSelected != -1) {
            this.setBorder(new TitledBorder(null, new listSort().listSortName.get(firstAlgorithmSelected), TitledBorder.LEADING, TitledBorder.TOP, null, null));
        }
        this.validate();
        this.repaint();
        this.setVisible(true);
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
